//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk.sdk
//


@class DVTFoldingLayoutManager, NSArray;

@protocol DVTFoldingLayoutManagerDelegate <NSLayoutManagerDelegate>
- (NSArray *)foldingTokenTypesForLayoutManager:(DVTFoldingLayoutManager *)arg1;

@optional
- (NSArray *)directoriesForLiteralFoldInLayoutManager:(DVTFoldingLayoutManager *)arg1;
- (void)layoutManager:(DVTFoldingLayoutManager *)arg1 didUnfoldRange:(struct _NSRange)arg2;
- (void)layoutManager:(DVTFoldingLayoutManager *)arg1 didFoldRange:(struct _NSRange)arg2;
@end

