/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol DVTTextStorageDelegate <NSTextStorageDelegate>

@optional
- (BOOL)textStorageShouldAllowEditing:(id)arg1;
- (void)textStorageDidUpdateSourceLandmarks:(id)arg1;
- (long long)nodeTypeForItem:(id)arg1 withContext:(id)arg2;
@end

