/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@class NSArray, NSAttributedString, NSImage, NSString;

@protocol DVTTextCompletionItem <NSObject>
@property(readonly) BOOL notRecommended;
@property double priority;
@property(readonly) NSImage *icon;
@property(readonly) NSAttributedString *descriptionText;
@property(readonly) NSString *parentText;
@property(readonly) NSString *completionText;
@property(readonly) NSString *displayType;
@property(readonly) NSString *displayText;
@property(readonly) NSString *name;

@optional
@property(readonly) NSImage *highlightedStatusIcon;
@property(readonly) NSImage *statusIcon;
@property(readonly) NSArray *additionalCompletions;
@property(readonly) int completionItemStyle;
- (void)infoViewControllerWithWidth:(double)arg1 context:(id)arg2 completionBlock:(id)arg3;
@end

