/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "DVTTextCompletionStrategy.h"

@interface DVTTextCompletionKeywordsStrategy : DVTTextCompletionStrategy
{
}

- (id)completionItemsForDocumentLocation:(id)arg1 context:(id)arg2 areDefinitive:(char *)arg3;
- (void)prepareForDocumentLocation:(id)arg1 context:(id)arg2;
- (id)_cachedKeywordCompletionsForLangSpecId:(id)arg1;
- (id)_keywordCompletionsForLangSpecId:(id)arg1;
- (id)_stringCompletionItemsForStringArray:(id)arg1;

@end

