/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@interface IDEOpenQuicklyPattern : NSObject
{
    NSString *_pattern;
    BOOL _patternHasSeparators;
    char *_charactersInPattern;
    unsigned short *_patternCharacters;
    unsigned short *_lowerCasePatternCharacters;
    unsigned long long _patternLength;
}

+ (id)patternWithInput:(id)arg1;
+ (void)initialize;
@property(readonly) NSString *pattern; // @synthesize pattern=_pattern;
- (double)scoreCandidate:(id)arg1 matchedRanges:(id *)arg2;
- (id)matchedRanges:(id)arg1;
- (double)scoreCandidate:(id)arg1;
- (BOOL)matchesCandidate:(id)arg1;
- (BOOL)matchesEverythingMatchedBy:(id)arg1;
- (BOOL)rejectsEverything;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToPattern:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithPattern:(id)arg1;

@end

